<a href="https://colab.research.google.com/github/niva1303-droid/Employee-Data-Cleaning-and-Feature-Engineering-using-Python/blob/main/Employee_Data_Cleaning_using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Employee Data Cleaning**

In [2]:
import numpy as np
import pandas as pd
import datetime as dt

In [3]:
# Upload File from Your Local System
# Import files module
from google.colab import files

# Upload file from local system
uploaded = files.upload()

#data frame conversion
df = pd.read_csv("Employee_data (1).csv")

Saving Employee_data (1).csv to Employee_data (1).csv

In [4]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

# **Initial Inspection**

In [5]:
print(df.head())

   Employee_ID      Name   Age Department        Position  Joining_Date  \
0         1000   hannah    NaN    finance     $Developer$  Sep 16, 2023
1         1001     ivan   30.0         it      Sr@Analyst     29-Aug-22
2         1002    frank   32.0         IT         Intern*    19-04-2023
3         1003    david    NaN         IT  Data-Scientist      02/14/23
4         1004     mike   28.0   finanace     $Developer$     16-Aug-19

   Salary   Feedback   Last_Login_Time Has_Car Useless_Col
0     70k       poor  11-11-2025 22:00       0         NaN
1  45,500  excellent  07-11-2025 05:00       0   remove_me
2     70k       good               NaN       1   remove_me
3   40000       poor  31-10-2025 19:00     NaN   remove_me
4   60000        NaN               NaN       1   remove_me

In [6]:
df_safe = df.copy()

In [7]:
df.head(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me

In [8]:
df.tail(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      205 non-null    int64
 1   Name             205 non-null    object
 2   Age              174 non-null    float64
 3   Department       205 non-null    object
 4   Position         205 non-null    object
 5   Joining_Date     205 non-null    object
 6   Salary           188 non-null    object
 7   Feedback         142 non-null    object
 8   Last_Login_Time  150 non-null    object
 9   Has_Car          186 non-null    object
 10  Useless_Col      112 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 17.7+ KB

In [10]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Position', 'Joining_Date',
       'Salary', 'Feedback', 'Last_Login_Time', 'Has_Car', 'Useless_Col'],
      dtype='object')

In [11]:
df.dtypes

Employee_ID          int64
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary              object
Feedback            object
Last_Login_Time     object
Has_Car             object
Useless_Col         object
dtype: object

In [12]:
df.describe()

       Employee_ID         Age
count   205.000000  174.000000
mean   1099.151220   37.528736
std      57.855902   21.307460
min    1000.000000   24.000000
25%    1049.000000   26.000000
50%    1099.000000   30.000000
75%    1149.000000   35.000000
max    1199.000000   90.000000

In [13]:
df.shape

(205, 11)

In [14]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             17
Feedback           63
Last_Login_Time    55
Has_Car            19
Useless_Col        93
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(5)

# **Data Cleaning and Transformation**

In [16]:
df.drop('Useless_Col', axis=1,inplace=True)

In [17]:
df.head()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1

In [18]:
df.shape

(205, 10)

In [19]:
df[df.duplicated(keep=False)]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
15,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
30,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
95,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
128,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No
158,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["Name"] = df["Name"].str.title().str.strip()

In [23]:
df.head()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,David,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1

In [24]:
df["Age"].describe()

count    169.000000
mean      37.733728
std       21.578900
min       24.000000
25%       26.000000
50%       30.000000
75%       35.000000
max       90.000000
Name: Age, dtype: float64

In [25]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [26]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [27]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,David,30.0,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,marketing,Sr@Analyst,07-07-2020,60000,poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,finanace,#Analyst,12-05-2021,"45,500",NaN,08-11-2025 16:00,0
197,1197,Alice,30.0,finance,Data-Scientist,14-02-2022,"65,000",good,11-11-2025 22:00,0
198,1198,Mike,32.0,IT,!Clerk,02/15/21,"45,500",average,NaN,1
199,1199,Kevin,28.0,it,$Developer$,15-Jul-20,40000,average,03-11-2025 16:00,Yes

In [28]:
df["Department"].unique()

array(['finance', 'it', 'IT', 'finanace', 'HR', 'FINANCE', 'sales',
       'MARKETING', 'hr', 'FINANACE', 'marketing', 'SALES'], dtype=object)

In [29]:
df["Department"].value_counts()

Department
it           26
finance      22
IT           21
HR           21
FINANCE      21
hr           20
sales        15
marketing    14
SALES        12
FINANACE     12
MARKETING    10
finanace      6
Name: count, dtype: int64

In [30]:
df["Department"] = df["Department"].str.title().str.strip()

In [31]:
df["Department"].unique()

array(['Finance', 'It', 'Finanace', 'Hr', 'Sales', 'Marketing'],
      dtype=object)

In [32]:
df["Department"] = df["Department"].replace("Finanace", "Finance")

In [33]:
df["Department"].unique()

array(['Finance', 'It', 'Hr', 'Sales', 'Marketing'], dtype=object)

In [34]:
df["Department"].value_counts()

Department
Finance      61
It           47
Hr           41
Sales        27
Marketing    24
Name: count, dtype: int64

In [35]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [36]:
df.head(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,It,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,It,Intern*,19-04-2023,70k,good,NaN,1

In [37]:
df["Position"] = df["Position"].str.replace(r'[^a-zA-Z]', ' ', regex=True).str.title().str.strip()

In [38]:
df["Position"].unique()

array(['Developer', 'Sr Analyst', 'Intern', 'Data Scientist', 'Manager',
       'Clerk', 'Analyst'], dtype=object)

In [39]:
df["Position"].value_counts()

Position
Data Scientist    32
Manager           31
Developer         29
Intern            28
Sr Analyst        28
Clerk             28
Analyst           24
Name: count, dtype: int64

In [40]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [41]:
df.dtypes

Employee_ID          int64
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary              object
Feedback            object
Last_Login_Time     object
Has_Car             object
dtype: object

In [42]:
df["Salary"].unique()

array(['70k', '45,500', '40000', '60000', nan, '65,000', '55000', '50000'],
      dtype=object)

In [43]:
df["Salary"].value_counts()

Salary
40000     33
60000     31
45,500    30
55000     27
70k       23
65,000    23
50000     17
Name: count, dtype: int64

In [44]:
df["Salary"] = df["Salary"].str.replace('k', '000').str.replace(',', '')

In [45]:
df["Salary"].unique()

array(['70000', '45500', '40000', '60000', nan, '65000', '55000', '50000'],
      dtype=object)

In [46]:
df["Salary"] = df["Salary"].astype(float)

In [47]:
df.dtypes

Employee_ID          int64
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary             float64
Feedback            object
Last_Login_Time     object
Has_Car             object
dtype: object

In [48]:
# Hierarchical imputation

# Level 1: Department + Position mean
dept_pos_mean = df.groupby(['Department','Position'])['Salary'].transform('mean')

# Level 2: Department mean
dept_mean = df.groupby('Department')['Salary'].transform('mean')

# Level 3: Overall mean
overall_mean = df['Salary'].mean()

# Hierarchical imputation
df["Salary"] = (df["Salary"].fillna(dept_pos_mean).fillna(dept_mean).fillna(overall_mean))

In [49]:
df["Salary"].unique()

array([70000.        , 45500.        , 40000.        , 60000.        ,
       54500.        , 65000.        , 51291.66666667, 54200.        ,
       55000.        , 61937.5       , 55083.33333333, 50000.        ,
       50909.09090909, 58000.        , 51250.        , 58100.        ,
       45000.        , 51642.85714286, 57583.33333333, 61250.        ])

In [50]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [51]:
df.head(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,It,Sr Analyst,29-Aug-22,45500.0,excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,It,Intern,19-04-2023,70000.0,good,NaN,1

In [52]:
df["Feedback"].unique()

array(['poor', 'excellent', 'good', nan, 'average', '?'], dtype=object)

In [53]:
df["Feedback"].value_counts()

Feedback
poor         31
good         29
average      29
?            26
excellent    25
Name: count, dtype: int64

In [54]:
df["Feedback"] = df["Feedback"].str.replace('?', 'average').str.title()

In [55]:
df["Feedback"] = df["Feedback"].fillna('Poor')

In [56]:
df["Feedback"].unique()

array(['Poor', 'Excellent', 'Good', 'Average'], dtype=object)

In [57]:
df["Feedback"].value_counts()

Feedback
Poor         91
Average      55
Good         29
Excellent    25
Name: count, dtype: int64

In [58]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback            0
Last_Login_Time    55
Has_Car            19
dtype: int64

In [59]:
df["Has_Car"].unique()

array(['0', '1', nan, 'No', 'Yes'], dtype=object)

In [60]:
df["Has_Car"].value_counts()

Has_Car
1      77
0      57
No     27
Yes    20
Name: count, dtype: int64

In [61]:
df["Has_Car"] = df["Has_Car"].replace({'0':'No', '1':'Yes'})

In [62]:
df['Has_Car'] = df['Has_Car'].fillna('No')

In [63]:
df.rename(columns={"Has_Car": "Car_Availability"}, inplace=True)

In [64]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Car_Availability
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,It,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,It,Intern,19-04-2023,70000.0,Good,NaN,Yes
3,1003,David,30.0,It,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,No
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,Poor,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,Poor,08-11-2025 16:00,No
197,1197,Alice,30.0,Finance,Data Scientist,14-02-2022,65000.0,Good,11-11-2025 22:00,No
198,1198,Mike,32.0,It,Clerk,02/15/21,45500.0,Average,NaN,Yes
199,1199,Kevin,28.0,It,Developer,15-Jul-20,40000.0,Average,03-11-2025 16:00,Yes

In [65]:
df["Car_Availability"].unique()

array(['No', 'Yes'], dtype=object)

In [66]:
df["Car_Availability"].value_counts()

Car_Availability
No     103
Yes     97
Name: count, dtype: int64

In [67]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Car_Availability
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,It,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,It,Intern,19-04-2023,70000.0,Good,NaN,Yes
3,1003,David,30.0,It,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,No
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,Poor,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,Poor,08-11-2025 16:00,No
197,1197,Alice,30.0,Finance,Data Scientist,14-02-2022,65000.0,Good,11-11-2025 22:00,No
198,1198,Mike,32.0,It,Clerk,02/15/21,45500.0,Average,NaN,Yes
199,1199,Kevin,28.0,It,Developer,15-Jul-20,40000.0,Average,03-11-2025 16:00,Yes

In [68]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], format = "mixed", errors="coerce", dayfirst = True)

In [70]:
df['Last_Login_Time'] = pd.to_datetime(df["Last_Login_Time"], format= "mixed", errors= "coerce", dayfirst = True)

In [71]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  0
Department           0
Position             0
Joining_Date         0
Salary               0
Feedback             0
Last_Login_Time     55
Car_Availability     0
dtype: int64

In [72]:
df['Last_Login_Time'] = df['Last_Login_Time'].fillna(df["Last_Login_Time"].mode()[0])

In [73]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback            0
Last_Login_Time     0
Car_Availability    0
dtype: int64

In [74]:
df.head(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Car_Availability
0,1000,Hannah,30.0,Finance,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No
1,1001,Ivan,30.0,It,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No
2,1002,Frank,32.0,It,Intern,2023-04-19,70000.0,Good,2025-11-02 18:00:00,Yes

In [76]:
df.dtypes

Employee_ID                  int64
Name                        object
Age                        float64
Department                  object
Position                    object
Joining_Date        datetime64[ns]
Salary                     float64
Feedback                    object
Last_Login_Time     datetime64[ns]
Car_Availability            object
dtype: object

In [ ]:
# Feature engineering means creating new useful columns (features) or transforming existing columns
# from the available data to make analysis or machine-learning models more meaningful.

In [77]:
df['Join_Year'] = df['Joining_Date'].dt.year

In [78]:
df['Salary'].describe()

count      200.000000
mean     54351.426407
std       9784.243180
min      40000.000000
25%      45500.000000
50%      55000.000000
75%      60000.000000
max      70000.000000
Name: Salary, dtype: float64

In [79]:
df["Salary_Range"]= pd.cut(df['Salary'],
                          bins=[0,40000,70000,float('inf')],
                          labels=['Low','Average','High'])

In [80]:
df["Login_Hour"]= df["Last_Login_Time"].dt.hour

In [81]:
df["Login_Status"]= np.where(df["Login_Hour"]<12,
                             "Early Login",
                             "Late Login")

In [82]:
df.head(3)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Car_Availability,Join_Year,Salary_Range,Login_Hour,Login_Status
0,1000,Hannah,30.0,Finance,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No,2023,Average,22,Late Login
1,1001,Ivan,30.0,It,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No,2022,Average,5,Early Login
2,1002,Frank,32.0,It,Intern,2023-04-19,70000.0,Good,2025-11-02 18:00:00,Yes,2023,Average,18,Late Login

#**Final Exploratory Data Analysis**

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       200 non-null    int64
 1   Name              200 non-null    object
 2   Age               200 non-null    float64
 3   Department        200 non-null    object
 4   Position          200 non-null    object
 5   Joining_Date      200 non-null    datetime64[ns]
 6   Salary            200 non-null    float64
 7   Feedback          200 non-null    object
 8   Last_Login_Time   200 non-null    datetime64[ns]
 9   Car_Availability  200 non-null    object
 10  Join_Year         200 non-null    int32
 11  Salary_Range      200 non-null    category
 12  Login_Hour        200 non-null    int32
 13  Login_Status      200 non-null    object
dtypes: category(1), datetime64[ns](2), float64(2), int32(2), int64(1), object(6)
memory usage: 20.6+ KB

In [84]:
df.describe()

,Employee_ID,Age,Joining_Date,Salary,Last_Login_Time,Join_Year,Login_Hour
count,200.000000,200.000000,200,200.000000,200,200.000000,200.000000
mean,1099.500000,36.535000,2021-05-29 15:14:24,54351.426407,2025-11-05 07:43:12,2020.940000,13.480000
min,1000.000000,24.000000,2018-01-11 00:00:00,40000.000000,2025-10-30 23:00:00,2018.000000,0.000000
25%,1049.750000,28.000000,2019-09-12 06:00:00,45500.000000,2025-11-02 18:00:00,2019.000000,7.000000
50%,1099.500000,30.000000,2021-07-04 12:00:00,55000.000000,2025-11-03 17:00:00,2021.000000,17.000000
75%,1149.250000,32.000000,2022-10-29 12:00:00,60000.000000,2025-11-08 20:15:00,2022.000000,18.000000
max,1199.000000,90.000000,2024-12-09 00:00:00,70000.000000,2025-11-12 07:00:00,2024.000000,23.000000
std,57.879185,20.024577,NaN,9784.243180,NaN,1.879912,6.768208

In [85]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback            0
Last_Login_Time     0
Car_Availability    0
Join_Year           0
Salary_Range        0
Login_Hour          0
Login_Status        0
dtype: int64